insert into `EXERCISE` (`name`) values ("Jumping Jacks");
insert into `EXERCISE` (`name`) values ("High Knees");
insert into `EXERCISE` (`name`) values ("Air Skip");
insert into `EXERCISE` (`name`) values ("Mountain Climbers");
insert into `EXERCISE` (`name`) values ("Alternating Lunge");
insert into `EXERCISE` (`name`) values ("Prisoner Squat");
insert into `EXERCISE` (`name`) values ("Half Burpee");
insert into `EXERCISE` (`name`) values ("Butt Kicks");
insert into `EXERCISE` (`name`) values ("Plank Step Out");
insert into `EXERCISE` (`name`) values ("Plank Roll");
insert into `EXERCISE` (`name`) values ("Squat + Side Jump");
insert into `EXERCISE` (`name`) values ("High Plank");
insert into `EXERCISE` (`name`) values ("Plank + Jumping Jack");
insert into `EXERCISE` (`name`) values ("Jump + Punches");
insert into `EXERCISE` (`name`) values ("Jump Squats");
insert into `EXERCISE` (`name`) values ("Twisting Mountain Climbers");
insert into `EXERCISE` (`name`) values ("Push Ups");
insert into `EXERCISE` (`name`) values ("Dolphin Hold");
insert into `EXERCISE` (`name`) values ("Plank Jump + Punches");
insert into `EXERCISE` (`name`) values ("Plank");
insert into `EXERCISE` (`name`) values ("High Side Plank Raise");
insert into `EXERCISE` (`name`) values ("Russian Twists");
insert into `EXERCISE` (`name`) values ("Switching Lunges");
insert into `EXERCISE` (`name`) values ("In & Outs");
insert into `EXERCISE` (`name`) values ("Jump Rope");
insert into `EXERCISE` (`name`) values ("On Spot Sprint");
insert into `EXERCISE` (`name`) values ("Lunges");
insert into `EXERCISE` (`name`) values ("One Leg Side Hops");
insert into `EXERCISE` (`name`) values ("Low Runner");
insert into `EXERCISE` (`name`) values ("Burpees");
insert into `EXERCISE` (`name`) values ("Jogging");
insert into `EXERCISE` (`name`) values ("Rest");
insert into `EXERCISE` (`name`) values ("Sumo Squats");
insert into `EXERCISE` (`name`) values ("Shoulder Tap Planks");